name: kyc_sharing_client
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cross_file: ^0.3.4+1
  cryptography: ^2.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  kyc_client_dart:
    path: ../
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  solana: ^0.30.4

dev_dependencies:
  mews_pedantic: ^0.28.0

flutter:
  uses-material-design: true
