name: kyc_client_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  cryptography: ^2.7.0
  dart_jsonwebtoken: ^2.14.0
  http: ^1.2.1
  pinenacl: ^0.6.0
  solana: ^0.30.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
